name: Studiotwofour Continous Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Main Code
        working-directory: main
        uses: actions/checkout@v2
        # - uses: actions/setup-node@master
        #   with:
        #     node-version: 12
        # - run: npm ci
        # - run: npm run build
        # - run: npm run generate
        run: |
          pwd
          ls
