name: Studiotwofour Continous Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Build dist
        working-directory: main
        run: |
          npm ci
          npm run build
          npm run generate
      - uses: actions/checkout@v2
        with:
          path: static
          repository: ihsanvp/studiotwofour-public

      # - name: Copy dist
      #   run: cp -TRv ./main/dist ./static
      # - name: Push repository
      #   working-directory: static
      #   run: |
      #     git add --all
      #     git commit -m 'deploy'
      #     git push
